- providers/openstack/scs/1-27/cluster-class/templates/openstack-machine-template-control-plane.yaml
- providers/openstack/scs/1-27/cluster-class/templates/openstack-machine-template-worker.yaml
- providers/openstack/scs/1-27/cluster-class/values.yaml
One parameter for the worker nodes and one for the controller nodes. With this parameter. All values that have been used in k8s-cluster-api-provider can now be set via helm.
> Adds parameters for server_group_id

- providers/openstack/alpha/1-28/csp-helper-chart/.helmignore
- providers/openstack/alpha/1-28/csp-helper-chart/Chart.yaml
- providers/openstack/alpha/1-28/csp-helper-chart/README.md
- providers/openstack/alpha/1-28/csp-helper-chart/templates/NOTES.txt
- providers/openstack/alpha/1-28/csp-helper-chart/templates/_helpers.tpl
- providers/openstack/alpha/1-28/csp-helper-chart/templates/cloud-secret.yaml
- providers/openstack/alpha/1-28/csp-helper-chart/templates/cluster-resource-set.yaml
- providers/openstack/alpha/1-28/csp-helper-chart/templates/namespace.yaml
- providers/openstack/alpha/1-28/csp-helper-chart/templates/openstack-workload-cluster-secret.yaml
- providers/openstack/alpha/1-28/csp-helper-chart/values.yaml
The chart can be used to transform a clouds.yaml in its unmodified form as retrieved from openstacks horizon ui into:
* a namespace with the same name as the openstack project
* a secret in that namespace with the contents of the clouds.yaml
* a secret containing a secret that contains the cloud.conf with credentials from the clouds.yaml in the format that is expected by OCCM
* a clusterresourceset to automatically transfer the OCCM secret to any correctly labeled workload cluster
Currently this only works with clouds.yaml with username and passwort. Application credential clouds.yaml may be added in the future
> Adds new helper chart

- providers/openstack/README.md
Currently a lot of short cuts are used in the Quickstart document. Even though there might be a glossary somewhere explaining them all the document is hard to read for people just willing to give the quickstart a go.
This commit adds an initial sentence properly introducing the short cuts so that the quickstart document should be easier to comprehend.
> :book: Introductory sentence introducing short cuts

- hack/docugen.py
PoC script to auto-generate markdown table from variable definitions of our cluster-class.
The script renders the `cluster-class.yaml` template using `helm template` and parses the `spec.variables` to generate a markdown table. The result is only printed to stdout currently.
The source `cluster-class.yaml` is hard-coded to `cluster-stacks/providers/openstack/scs/1-27/cluster-class/` as of right now. This needs to be adapted once the consolidation of the directory structure (#56) is done.
Usage:
To use the script, the [pyyaml library](https://github.com/yaml/pyyaml) needs to be installed.
```
python cluster-stacks/hack/docugen.py
```
The output can then be copied to a markdown file, redirected to a file:
```
python cluster-stacks/hack/docugen.py > <destination_file>.md
```
or piped to …
> added: script to generate markdown table

- providers/openstack/README.md
Fixes error in clusterstack manifest:
`The ClusterStack "clusterstack" is invalid: spec.kubernetesVersion: Invalid value: "number": spec.kubernetesVersion in body must be of type string: "number"
`
> fix spec.kubernetesVersion must be type string

- providers/openstack/README.md
When using the latest version of CSO(v0.1.0-alpha.6), the RuntimeSDK feature flag needs to be enabled, otherwise you get this error:
```
Error from server (Forbidden): error when creating "STDIN": admission webhook "validation.extensionconfig.runtime.cluster.x-k8s.io" denied the request: spec: Forbidden: can be set only if the RuntimeSDK feature flag is enabled
```
Fixes #128
> :book: Update quickstart guide

- providers/openstack/scs/cluster-addon-values.yaml
This PR sets the cluster name in the OCCM to make the name for the ingress-nginx load balancer unique
Fixes https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/495
Tested with the cluster name set to `cs-cluster`:
```
k describe po openstack-cloud-controller-manager-9l724 -n kube-system --kubeconfig cs-cluster.kubeconfig
Containers:
openstack-cloud-controller-manager:    
Environment:
CLOUD_CONFIG:  /etc/config/cloud.conf
CLUSTER_NAME:  cs-cluster
```
After the installation of Ingress-NGINX, the load balancer was created in the `gx-scs` with the expected name, see attached …
> :sparkles: Set cluster name in the OCCM

- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
Fixes #129 
**TODOs**:
```ZUUL_CONFIG
cluster_stack = "providers/openstack/scs"
```
> fix(cluster-class): options from different api versions somehow mixed up

- providers/openstack/README.md
- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
- providers/openstack/scs/cluster-class/templates/kubeadm-config-template-worker-openstack.yaml
- providers/openstack/scs/cluster-class/templates/openstack-machine-template-worker.yaml
> chore(cluster-class): rename machineDeployments

- providers/openstack/scs/cluster-class/templates/openstack-cluster-template.yaml
- providers/openstack/scs/cluster-class/templates/openstack-machine-template-control-plane.yaml
- providers/openstack/scs/cluster-class/templates/openstack-machine-template-worker.yaml
Remove unnecessary default values ​​from OpenStackClusterTemplate, which are not needed cause they are defined in the values.yaml
> :bug: Remove unnecessary default values ​​from OpenStackClusterTemplate and OpenStackMachineTemplates

- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
- providers/openstack/scs/cluster-class/templates/openstack-cluster-template.yaml
This PR adds security rules for the Cilium into the default security groups for control-plane and worker nodes.
Fixes #74 
This is how security groups for control-plane and worker nodes look like now:
> :sparkles: Manage Security Groups using OpenStackClusterTemplate

- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
- providers/openstack/scs/cluster-class/templates/openstack-cluster-template.yaml
- providers/openstack/scs/cluster-class/values.yaml
As of the latest [CAPO docs](https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration#external-network) it's possible to leave the external network ID empty if there is only a one external network which will be picked automatically.
Fixes #100
> :sparkles: Possibility to leave external network ID empty

- .zuul.yaml
- playbooks/openstack/e2e.yaml
- playbooks/openstack/templates/cluster.yaml.j2
- providers/openstack/scs/cluster-class/values.yaml
> :bug: Adjust e2e test after the repo structure has changed

- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
This PR adds an option to specify network MTU via variable in your cluster resource
Fixes #149 
Tested with `cluster.yaml` file, which looks like:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
name: cs-cluster
labels:
managed-secret: cloud-config
spec:
clusterNetwork:
pods:
cidrBlocks:
- 192.168.0.0/16
serviceDomain: cluster.local
services:
cidrBlocks:
- 10.96.0.0/12
topology:
variables:
- name: controller_flavor
value: "SCS-2V-4-50"
- name: worker_flavor
value: "SCS-2V-4-50"
- name: network_mtu
value: 1420
class: …
```
> :sparkles: Add network MTU variable into cluster-class

- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
> :sparkles: Add controlPlaneAvailabilityZones and controlPlaneOmitAvailabilityZone variables

- providers/openstack/scs/cluster-addon/values.yaml
Fixes SovereignCloudStack/moin-cluster-config#43
**TODOs**:
> Add default storage class

- docs/providers/openstack/quickstart.md
This PR fixes the quickstart guide, which contains an incorrect Kubernetes patch version for the given cluster stack.
**TODOs**:
> :book: Fix CS_K8S_PATCH_VERSION variable in quickstart guide

- providers/openstack/scs/cluster-class/templates/cluster-class.yaml
- providers/openstack/scs/cluster-class/templates/openstack-cluster-template.yaml
- providers/openstack/scs/cluster-class/values.yaml
> :bug: Fix kube-vip apiserver load balancer

- docs/providers/openstack/quickstart.md
Avoid the gettext envsubst trap.
Fixes #191.
This is the minimal fix for #191. As soon as we have something better, this can of course be superceded again.
> :book: Tell user to avoid the distro envsubst.

- docs/providers/openstack/quickstart.md
- providers/openstack/kamaji/1-30/cluster-class/templates/cluster-class.yaml
- providers/openstack/kamaji/1-30/cluster-class/values.yaml
- providers/openstack/scs/cluster-class/values.yaml
Example should work broadly, so use flavors that always exist.
Fixes #190.
I will check whether we should also touch some defaults ...
> :book: Use always present SCS flavors in example.

- providers/openstack/scs/cluster-addon/values.yaml
Cilium doesn't use the IP settings from `Cluster.spec.clusterNetwork` because it has its own IPAM mode.
Since we currently don't need the extra features of Cilium, we'll set it to Kubernetes mode.
Fixes #198 
**TODOs**:
> feat(cluster-addon): Use IPAM mode Kubernetes

- hack/generate_version.py
Needed for refactored scs cluster stacks.
**TODOs**:
> Fix generate_version.py for cluster addons with multiple charts

- providers/openstack/scs2/README.md
- providers/openstack/scs2/cluster-addon/ccm/Chart.yaml
- providers/openstack/scs2/cluster-addon/ccm/overwrite.yaml
- providers/openstack/scs2/cluster-addon/ccm/values.yaml
- providers/openstack/scs2/cluster-addon/cni/Chart.yaml
- providers/openstack/scs2/cluster-addon/cni/values.yaml
- providers/openstack/scs2/cluster-addon/csi/Chart.yaml
- providers/openstack/scs2/cluster-addon/csi/overwrite.yaml
- providers/openstack/scs2/cluster-addon/csi/values.yaml
- providers/openstack/scs2/cluster-addon/metrics-server/Chart.yaml
- providers/openstack/scs2/cluster-addon/metrics-server/overwrite.yaml
- providers/openstack/scs2/cluster-addon/metrics-server/values.yaml
- providers/openstack/scs2/cluster-class/.helmignore
- providers/openstack/scs2/cluster-class/Chart.yaml
- providers/openstack/scs2/cluster-class/templates/_helpers.tpl
- providers/openstack/scs2/cluster-class/templates/cluster-class.yaml
- providers/openstack/scs2/cluster-class/templates/kubeadm-config-template-worker-openstack.yaml
- providers/openstack/scs2/cluster-class/templates/kubeadm-control-plane-template.yaml
- providers/openstack/scs2/cluster-class/templates/openstack-cluster-template.yaml
- providers/openstack/scs2/cluster-class/templates/openstack-machine-template-control-plane.yaml
- providers/openstack/scs2/cluster-class/templates/openstack-machine-template-worker.yaml
- providers/openstack/scs2/clusteraddon.yaml
- providers/openstack/scs2/csctl.yaml
- providers/openstack/scs2/versions.yaml
Hi @garloff and @matofeder,
as discussed this is a PR containing the new Cluster Stack `scs2`.
The addons are already adjusted to use the `clouds.yaml` instead of generated `cloud.conf` (makes openstack-csp-helper unnecessary) (#225), also some variables are already renamed using lower camel case.
- What happens when changing from `scs` to `scs2` ClusterClass?
- Rename variables (capi controller will complain anyway)
- CSPO can be removed
- change managed secret
- ORC needs to be added (if not present already)
- ...
> Add SCS2 Cluster Stacks
